[project]
name = "bindicator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "peewee>=3.19.0",
    "rpi-gpio>=0.7.1",
    "rplcd>=1.4.0",
    "schedule>=1.2.2",
    "uk-bin-collection>=0.162.6",
    "fastapi[standard]>=0.128.0",
    "sqlalchemy>=2.0.46",
    "alembic>=1.18.3",
    "pydantic>=2.12.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
