/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bins/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bins
         * @description Get a paginated list of bins.
         */
        get: operations["get_bins_bins__get"];
        put?: never;
        /**
         * Create Bin
         * @description Create a new bin.
         */
        post: operations["create_bin_bins__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bins/{bin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bin
         * @description Get a bin by its ID.
         */
        get: operations["get_bin_bins__bin_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Bin
         * @description Delete a bin by its ID.
         */
        delete: operations["delete_bin_bins__bin_id__delete"];
        options?: never;
        head?: never;
        /**
         * Edit Bin
         * @description Edit a bin's name and colour.
         */
        patch: operations["edit_bin_bins__bin_id__patch"];
        trace?: never;
    };
    "/bins/{bin_id}/move-earlier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Bin Earlier
         * @description Move a bin earlier in the order.
         */
        post: operations["move_bin_earlier_bins__bin_id__move_earlier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bins/{bin_id}/move-later": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Bin Later
         * @description Move a bin later in the order.
         */
        post: operations["move_bin_later_bins__bin_id__move_later_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bins/{bin_id}/set-position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Bin Position
         * @description Set the position of a bin.
         */
        post: operations["set_bin_position_bins__bin_id__set_position_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hardware/restart/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Application
         * @description Restart the hardware application.
         */
        post: operations["restart_application_hardware_restart__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schedules
         * @description Get all schedules paginated.
         */
        get: operations["list_schedules_schedules__get"];
        put?: never;
        /**
         * Create Schedule
         * @description Create a new schedule.
         */
        post: operations["create_schedule_schedules__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load Calendar
         * @description Get computed bin collection dates within a date range.
         *     Considers schedules and bin day replacements.
         */
        get: operations["load_calendar_schedules_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule
         * @description Get a schedule by its ID.
         */
        get: operations["get_schedule_schedules__schedule_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Schedule
         * @description Delete a schedule by its ID.
         */
        delete: operations["delete_schedule_schedules__schedule_id__delete"];
        options?: never;
        head?: never;
        /**
         * Edit Schedule
         * @description Edit an existing schedule.
         */
        patch: operations["edit_schedule_schedules__schedule_id__patch"];
        trace?: never;
    };
    "/bin_day_replacements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bin Day Replacements */
        get: operations["list_bin_day_replacements_bin_day_replacements__get"];
        put?: never;
        /** Create Bin Day Replacement */
        post: operations["create_bin_day_replacement_bin_day_replacements__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bin_day_replacements/{replacement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bin Day Replacement */
        get: operations["get_bin_day_replacement_bin_day_replacements__replacement_id__get"];
        put?: never;
        post?: never;
        /** Delete Bin Day Replacement */
        delete: operations["delete_bin_day_replacement_bin_day_replacements__replacement_id__delete"];
        options?: never;
        head?: never;
        /** Edit Bin Day Replacement */
        patch: operations["edit_bin_day_replacement_bin_day_replacements__replacement_id__patch"];
        trace?: never;
    };
    "/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Get the current settings.
         */
        get: operations["get_settings_settings__get"];
        put?: never;
        /**
         * Create Or Update Settings
         * @description Create new settings. This will overwrite existing settings.
         */
        post: operations["create_or_update_settings_settings__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Setting
         * @description Delete a specific setting by name.
         */
        delete: operations["delete_setting_settings__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bin-put-outs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bin Put Outs
         * @description Get a paginated list of bin put out records.
         */
        get: operations["get_bin_put_outs_bin_put_outs__get"];
        put?: never;
        /**
         * Create Bin Put Out
         * @description Create a new bin put out record.
         */
        post: operations["create_bin_put_out_bin_put_outs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bin-put-outs/by-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bin Put Outs By Date
         * @description Get all bins put out on a specific date.
         */
        get: operations["get_bin_put_outs_by_date_bin_put_outs_by_date_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bin-put-outs/{put_out_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bin Put Out
         * @description Get a bin put out record by its ID.
         */
        get: operations["get_bin_put_out_bin_put_outs__put_out_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Bin Put Out
         * @description Delete a bin put out record by its ID.
         */
        delete: operations["delete_bin_put_out_bin_put_outs__put_out_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Bin */
        Bin: {
            /** Name */
            name: string;
            /** Colour */
            colour?: string | null;
            /** Id */
            id: number;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BinCreate */
        BinCreate: {
            /** Name */
            name: string;
            /** Colour */
            colour?: string | null;
        };
        /** BinDayReplacement */
        BinDayReplacement: {
            /**
             * Replace
             * Format: date-time
             */
            replace: string;
            /**
             * Replace With
             * Format: date-time
             */
            replace_with: string;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BinDayReplacementCreate */
        BinDayReplacementCreate: {
            /**
             * Replace
             * Format: date-time
             */
            replace: string;
            /**
             * Replace With
             * Format: date-time
             */
            replace_with: string;
        };
        /** BinEdit */
        BinEdit: {
            /** Name */
            name?: string | null;
            /** Colour */
            colour?: string | null;
        };
        /** BinPutOut */
        BinPutOut: {
            /** Bin Id */
            bin_id: number;
            /**
             * Date Put Out At
             * Format: date-time
             */
            date_put_out_at: string;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BinPutOutCreate */
        BinPutOutCreate: {
            /** Bin Id */
            bin_id: number;
            /**
             * Date Put Out At
             * Format: date-time
             */
            date_put_out_at: string;
        };
        /** CalendarBin */
        CalendarBin: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Colour */
            colour?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "missed" | "taken_out" | "due_out" | "not_yet_due";
            /** Put Out Date */
            put_out_date?: string | null;
        };
        /** CalendarDate */
        CalendarDate: {
            /** Date */
            date: string;
            /** Bins */
            bins: components["schemas"]["CalendarBin"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginationResponse[BinDayReplacement] */
        PaginationResponse_BinDayReplacement_: {
            /** Items */
            items: components["schemas"]["BinDayReplacement"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
        };
        /** PaginationResponse[BinPutOut] */
        PaginationResponse_BinPutOut_: {
            /** Items */
            items: components["schemas"]["BinPutOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
        };
        /** PaginationResponse[Bin] */
        PaginationResponse_Bin_: {
            /** Items */
            items: components["schemas"]["Bin"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
        };
        /** PaginationResponse[Schedule] */
        PaginationResponse_Schedule_: {
            /** Items */
            items: components["schemas"]["Schedule"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
        };
        /** Schedule */
        Schedule: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** End */
            end?: string | null;
            /** Bin Id */
            bin_id: number;
            /** Repeat Weeks */
            repeat_weeks: number;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScheduleCreate */
        ScheduleCreate: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** End */
            end?: string | null;
            /** Bin Id */
            bin_id: number;
            /** Repeat Weeks */
            repeat_weeks: number;
        };
        /** ScheduleEdit */
        ScheduleEdit: {
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /** Bin Id */
            bin_id?: number | null;
            /** Repeat Weeks */
            repeat_weeks?: number | null;
        };
        /** SettingsBase */
        SettingsBase: {
            /**
             * Timeout
             * @default 120
             */
            timeout: number;
            /**
             * Put Out Day Before
             * @default false
             */
            put_out_day_before: boolean;
            /**
             * Put Out Time
             * @default 17:00
             */
            put_out_time: string;
            /**
             * Collection Time
             * @default 09:00
             */
            collection_time: string;
        };
        /** SettingsEdit */
        SettingsEdit: {
            /** Timeout */
            timeout?: number | null;
            /** Put Out Day Before */
            put_out_day_before?: boolean | null;
            /** Put Out Time */
            put_out_time?: string | null;
            /**
             * Collection Time
             * @default 09:00
             */
            collection_time: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_bins_bins__get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponse_Bin_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bin_bins__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BinCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bin_bins__bin_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bin_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bin_bins__bin_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bin_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_bin_bins__bin_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bin_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BinEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_bin_earlier_bins__bin_id__move_earlier_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bin_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_bin_later_bins__bin_id__move_later_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bin_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_bin_position_bins__bin_id__set_position_post: {
        parameters: {
            query: {
                position: number;
            };
            header?: never;
            path: {
                bin_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_application_hardware_restart__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_schedules_schedules__get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponse_Schedule_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_schedule_schedules__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_calendar_schedules_calendar_get: {
        parameters: {
            query: {
                /** @description Start date (YYYY-MM-DD) */
                start: string;
                /** @description End date (YYYY-MM-DD) */
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarDate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_schedules__schedule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_schedule_schedules__schedule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_schedule_schedules__schedule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bin_day_replacements_bin_day_replacements__get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponse_BinDayReplacement_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bin_day_replacement_bin_day_replacements__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BinDayReplacementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinDayReplacement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bin_day_replacement_bin_day_replacements__replacement_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replacement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinDayReplacement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bin_day_replacement_bin_day_replacements__replacement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replacement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_bin_day_replacement_bin_day_replacements__replacement_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                replacement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinDayReplacement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBase"];
                };
            };
        };
    };
    create_or_update_settings_settings__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_setting_settings__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bin_put_outs_bin_put_outs__get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponse_BinPutOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bin_put_out_bin_put_outs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BinPutOutCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinPutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bin_put_outs_by_date_bin_put_outs_by_date_get: {
        parameters: {
            query: {
                /** @description Date in YYYY-MM-DD format */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinPutOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bin_put_out_bin_put_outs__put_out_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                put_out_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinPutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bin_put_out_bin_put_outs__put_out_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                put_out_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
